name: Build
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'
  push:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md'

jobs:
  macos-build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v7

      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90
        with:
          xcode-version: 16.4

      - name: Install CocoaPods dependencies
        run: pod install

      - name: Build hello-ios-swift
        run: set -o pipefail && xcodebuild build -workspace 'hello-ios-swift.xcworkspace' -scheme 'hello-ios-swift' CODE_SIGNING_ALLOWED=NO | xcpretty
